version: '3'

services:
  orb:
    image: orb:latest
    env_file: ./conf/config.yaml
    depends_on:
      - mock-api
  mock-api:
    image: mockserver/mockserver:5.15.0
    ports:
        - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /mocks/mocks.json
    volumes:
      - type: bind
        source: ./mocks
        target: /mocks
